application: ringio-blog
version: 8
runtime: python
api_version: 1
skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (.*/\.svn/.*)|
 (.*/Thumbs\.db)|
 )$


handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /img
  static_dir: img

- url: /jscripts
  static_dir: jscripts

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico
  
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /crossdomain.xml
  static_files: img/crossdomain.xml
  upload: img/crossdomain.xml

- url: /static
  static_dir: static

- url: /canvas.html
  static_files: jscripts/friendconnect/canvas.html
  upload: jscripts/friendconnect/canvas.html

- url: /rpc_relay.html
  static_files: jscripts/friendconnect/rpc_relay.html
  upload: jscripts/friendconnect/rpc_relay.html  

- url: /appadmin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /login*
  script: main.py
  login: admin

- url: /.*
  script: main.py

